# Dockerfile_mysql 파일명으로 다음과 같이 작성

FROM mysql:latest

# mysql 슈퍼관리자인 root ID에 대한 password 란에 원하는 패스워드 설정
ENV MYSQL_ROOT_PASSWORD=password
# dbname란에 원하는 데이터베이스 이름 설정
ENV MYSQL_DATABASE=dbname

# 필요시 다음 설정도 가능
# user란에 mysql 추가 사용자 id 설정
# ENV MYSQL_USER=user 
# pw란에 mysql 추가 사용자 id 의 패스워드 설정
# ENV MYSQL_PASSWORD=pw
