FROM httpd:18.04

LABEL maintainer="test@site.org"
LABEL version="1.0.0"
LABEL description="docker test"

RUN apt-get update # 패키지 정보 업데이트

# apache2 패키지 설치, 중간에 y/n 묻는 단계가 나오면 모드 Yes로 하고 설치
RUN apt-get install -y apache2 

# apache2 디폴트 웹서버 설정은 /var/www/html/ 폴더의 웹페이지를 보여줌
COPY ./data /var/www/html

# apache2 웹서버 구동 명령은 다음과 같음
ENTRYPOINT ["/usr/sbin/apache2ctl","-D","FOREGROUND"]
