FROM ubuntu

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1
ENV TZ=Asia/Seoul
ENV DEBIAN_FRONTEND=noninteractive


RUN apt update  && apt install -y git
RUN apt install -y build-essential
RUN apt update  
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt update && apt install -y python3.9

RUN apt-get update && apt-get install -y python3
RUN apt-get install -y python3-pip && pip install --upgrade pip

# git clone
RUN git clone https://github.com/shimseonjo1/djangotest.git .

RUN pip install -r requirements.txt
#RUN ls /usr/bin/python
#RUN python manage.py makemigrations
#RUN python manage.py migrate

CMD python manage.py runserver 0.0.0.0:8000
